---------------------------------------------------------------------------
--                                                                       --
--                                                                       --
--                                                                       --
--                                                                       --
--                                                                       --
--         Incidental dependencies in a client/server architecture       --
--                                                                       --
--           1. Incidental dependencies                                  --
--         > 2. Serializable updates                                     --
--           3. Datatype-generic programming                             --
--           4. Type-safe diff for families of datatypes (gdiff)         --
--           5. Datatype-generic diff                                    --
--                                                                       --
--                                                                       --
--                                                                       --
--                                                                       --
--                                                                       --
--                                                                       --
--                                                                       --
---------------------------------------------------------------------------
