name: write-your-own-frp
dependencies:
  - JuicyPixels
  - array
  - base
  - deepseq
  - doctest
  - gloss
  - gloss-juicy
  - lens
  - process
executable:
  main: Slide
  source-dirs: src
  default-extensions:
    - GADTs
    - InstanceSigs
    - LambdaCase
    - PatternSynonyms
    - RankNTypes
    - RecordWildCards
    - ScopedTypeVariables
    - TemplateHaskell
    - TupleSections
    - ViewPatterns
