#compiler: ghc-git-89d9e554a4e87a8ea45ee77a6a60d972f4eca726-quick
#compiler-repository: git@gitlab.haskell.org:trac-isovector/ghc.git
#
#resolver: lts-13.18
#resolver: lts-12.19
#compiler: ghc-7.8.4
#compiler: ghc-8.6.3
resolver: lts-14.1
#resolver: lts-9.21
#resolver: lts-2.22
allow-newer: true
packages:
  - .
extra-deps:
  - reactive-banana-1.2.1.0
  - non-empty-zipper-0.1.0.9
  - terminal-0.2.0.0
