-------------------------------------------------
--                                             --
--            Haskell-only tricks              --
--       which won't work anywhere else        --
--                                             --
--                                             --
--     1. Laziness.                            --
--                                             --
--     2. Point-free syntax.                   --
--                                             --
--        Functions often pass most of their   --
--        arguments, unmodified, to a helper   --
--        function.                            --
--                                             --
--        Haskell has a shorter syntax for     --
--        this common case.                    --
--                                             --
--                                             --
-------------------------------------------------
