-------------------------------------------------
--                                             --
--            Haskell-only tricks              --
--       which won't work anywhere else        --
--                                             --
--                                             --
--     1. Laziness.                            --
--                                             --
--        Without language support, you would  --
--        need to wrap everything in a thunk.  --
--                                             --
--        This gets old real quick.            --
--                                             --
--                                             --
--                                             --
--                                             --
--                                             --
--                                             --
------------------------------------------------
